---
title: "01-haws-meta"
output: html_document
---

https://github.com/RobertsLab/resources/issues/1372

wrong file
```{bash}
curl --insecure -O https://gannet.fish.washington.edu/spartina/project-oyster-oa/Haws/project-oyster-oa.RData
```


```{r}
load("../data/project-oyster-oa.RData")
```


try again

https://gannet.fish.washington.edu/spartina/project-oyster-oa/Haws/methylKit/methylKit.RData


```{bash}
curl --insecure -O https://gannet.fish.washington.edu/spartina/project-oyster-oa/Haws/methylKit/methylKit.RData
```




```{r}
load("../data/methylKit.RData")
```


## Comparative analysis


```{r}
library(methylKit)
```

```{r}
methylationInformationFilteredCov5 <- methylKit::unite(processedFilteredFilesCov5,
                                                       destrand = FALSE) #Combine all processed files into a single table. Use destrand = TRUE to not destrand. By default only bases with data in all samples will be kept
head(methylationInformationFilteredCov5) #Confirm unite
```





